spring:
  data:
    redis:
      #spring.data.redis.use-redis-cache
      use-redis-cache: true
      host: localhost # Default to 'localhost' if not provided
      #host: ${REDIS_HOST:ubuntu-server-01.local} # Default to 'localhost' if not provided
      port: 6379      # Default to 6379 if not provided
  application:
    name: StepUp
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      use-redis-cache: true
#      time-to-live: 60000  # Thời gian sống của cache (ms)

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect  # Dialect H2 cho Hibernate
#    show-sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#  datasource:
#    url: jdbc:mysql://localhost:3306/stepup
#    username: root
#    password: 1234567890

  datasource:
    url: jdbc:mysql://mainline.proxy.rlwy.net:51159/railway
    username: root
    password: ddzxzgBdcxBYdJiYBiRrkatfYwVtsvsl

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: laptrinhh2208@gmail.com
    password: bewq lkvf au sasu
    properties.mail:
      smtp:
        auth: true
        starttls.enable: true

server:
  port: 8089

maximum_per_product: 6

api:
  prefix: /api/v1